export const questions = [
    {
        "uuid": "",
        "title": "",
        "body": "",
        "createdAt": "",
        "forumID": "",
        "topicsID": "",
        "UserId": "",
    },
    {
        "uuid": "",
        "title": "",
        "body": "",
        "createdAt": "",
        "forumID": "",
        "topicsID": "",
        "UserId": "",
    },
    {
        "uuid": "",
        "title": "",
        "body": "",
        "createdAt": "",
        "forumID": "",
        "topicsID": "",
        "UserId": "",
    },
    {
        "uuid": "",
        "title": "",
        "body": "",
        "createdAt": "",
        "forumID": "",
        "topicsID": "",
        "UserId": "",
    },
    {
        "uuid": "",
        "title": "",
        "body": "",
        "createdAt": "",
        "forumID": "",
        "topicsID": "",
        "UserId": "",
    },
    {
        "uuid": "",
        "title": "",
        "body": "",
        "createdAt": "",
        "forumID": "",
        "topicsID": "",
        "UserId": "",
    },
]

